name: Build and Publish

on:
  pull_request:
    branches:
      - master

jobs:
  build-75x-118x:
    runs-on: ubuntu-latest
    name: Build 7.5.x - 1.18.x
    steps:
    - uses: actions/checkout@v1

    - name: Build 7.5.0-1.18.9 image
      run: docker build --tag wunderio/elasticsearch-readonlyrest:7.5.0-1.18.9 --build-arg "ES_VERSION=7.5.0" --build-arg "ES_ROR_VERSION=1.18.9" .
  build-68x-118x:
    runs-on: ubuntu-latest
    name: Build 6.8.x - 1.18.x
    steps:
    - uses: actions/checkout@v1

    - name: Build 6.8.5-1.18.9 image
      run: docker build --tag wunderio/elasticsearch-readonlyrest:6.8.5-1.18.9 --build-arg "ES_VERSION=6.8.5" --build-arg "ES_ROR_VERSION=1.18.9" .

    - name: Build 6.8.4-1.18.9 image
      run: docker build --tag wunderio/elasticsearch-readonlyrest:6.8.4-1.18.9 --build-arg "ES_VERSION=6.8.4" --build-arg "ES_ROR_VERSION=1.18.9" .

